/**
 * Generator — Auto-implements skill suggestions.
 *
 * Takes a suggestion object and generates a working skill file
 * that can be installed directly into Claude Code, Codex, or Gemini CLI.
 *
 * Skill files are markdown with YAML frontmatter (Claude Code format).
 * The generator produces a template and, where possible, a working
 * implementation with the right tool calls and instructions.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { homedir } from "os";

// Map suggestion sources to implementation strategies
const STRATEGIES = {
  // URL pattern skills → typically read data from an API or scrape
  url_pattern: generateApiSkill,
  // App usage skills → typically automate app interactions
  app_usage: generateAppSkill,
  // Context switch skills → typically bridge two tools
  context_switch: generateBridgeSkill,
  // Repeated text → template/snippet
  repeated_text: generateTemplateSkill,
};

/**
 * Generate a skill file from a suggestion.
 * Returns { path, content, installed } or null if it can't generate.
 */
export function generateSkill(suggestion, options = {}) {
  const {
    outputDir = join(homedir(), ".claude/commands"),
    brainDir = join(homedir(), "brain/skills"),
    dryRun = false,
  } = options;

  const strategy = STRATEGIES[suggestion.source];
  if (!strategy) return null;

  const content = strategy(suggestion);
  const filename = `${suggestion.id}.md`;
  const outputPath = join(outputDir, filename);
  const brainPath = join(brainDir, filename);

  if (dryRun) {
    return { path: outputPath, brainPath, content, installed: false };
  }

  // Write to Claude Code commands dir (installed)
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);

  // Write canonical copy to brain repo
  mkdirSync(dirname(brainPath), { recursive: true });
  writeFileSync(brainPath, content);

  return { path: outputPath, brainPath, content, installed: true };
}

function generateApiSkill(suggestion) {
  // Skills that pull data from web services / APIs
  const implementations = {
    "meeting-auto-brief": meetingAutoBrief,
    "pr-dashboard": prDashboard,
    "model-cost-monitor": modelCostMonitor,
    "credential-audit": credentialAudit,
    "slack-integration-health": slackHealth,
  };

  const impl = implementations[suggestion.id];
  if (impl) return impl(suggestion);
  return genericApiSkill(suggestion);
}

function generateAppSkill(suggestion) {
  const implementations = {
    "expense-monitor": expenseMonitor,
    "video-cataloger": videoCataloger,
    "tab-audit": tabAudit,
    "bookmark-manager": bookmarkManager,
  };

  const impl = implementations[suggestion.id];
  if (impl) return impl(suggestion);
  return genericAppSkill(suggestion);
}

function generateBridgeSkill(suggestion) {
  return `---
name: ${suggestion.id}
description: "${suggestion.description}"
---

# ${suggestion.id}

> Auto-generated by skill-engine from telemetry data.
> Signal: ${suggestion.signal}

## Context
This skill bridges a frequent workflow transition detected in your activity data.

## Instructions
When the user is working in this workflow pattern, proactively:
1. Detect the transition context
2. Carry relevant state between the tools
3. Reduce manual copy/paste or context-switching overhead

## TODO
This is a template — refine the implementation based on the specific workflow.
`;
}

function generateTemplateSkill(suggestion) {
  return `---
name: ${suggestion.id}
description: "${suggestion.description}"
---

# ${suggestion.id}

> Auto-generated by skill-engine from keystroke analysis.
> Signal: ${suggestion.signal}

## Template
Expand this template when the user starts typing the detected pattern.

## TODO
Add the actual template text and any variable substitution logic.
`;
}

function genericApiSkill(suggestion) {
  return `---
name: ${suggestion.id}
description: "${suggestion.description}"
---

# ${suggestion.id}

> Auto-generated by skill-engine.
> Signal: ${suggestion.signal}

## Instructions
${suggestion.description}

## TODO
Implement the data fetching and formatting logic.
`;
}

function genericAppSkill(suggestion) {
  return genericApiSkill(suggestion);
}

// ─── Specific implementations ───────────────────────────────────

function meetingAutoBrief(s) {
  return `---
name: meeting-auto-brief
description: "Auto-generate pre-meeting context from brain repo + Memory Engine before Google Meet calls"
---

# Meeting Auto-Brief

> Signal: ${s.signal}

Before joining a Google Meet call, generate a brief with:

## Steps

1. **Identify the meeting** — check Google Calendar for the next meeting via gcal MCP
2. **Find participants** — look up attendee profiles in \`~/brain/profiles/people/\`
3. **Search Memory Engine** — query for recent interactions with these people:
\`\`\`bash
curl -s "http://3.137.184.167:3100/v1/memories/search" \\
  -H "Authorization: Bearer $MEMORY_ENGINE_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"query": "<participant names + company>", "limit": 5}'
\`\`\`
4. **Check open issues** — any GitHub issues related to this person/project
5. **Output a brief** — 5-10 bullet points: who they are, last interaction, open items, talking points

## Output Format
Present as a concise brief that can be scanned in 30 seconds before the call starts.
`;
}

function prDashboard(s) {
  return `---
name: pr-dashboard
description: "Morning summary of open PRs, review requests, and CI status across all repos"
---

# PR Dashboard

> Signal: ${s.signal}

Run this during SOD to get a quick view of open PRs.

## Steps

1. **List open PRs across key repos**:
\`\`\`bash
for repo in Scottpedia0/brain Scottpedia0/relay go2impact/Town-Hall; do
  echo "## $repo"
  gh pr list -R "$repo" --state open --limit 10
done
\`\`\`

2. **Check CI status** on each open PR:
\`\`\`bash
gh pr checks <pr-number> -R <repo>
\`\`\`

3. **Review requests** — flag any PRs waiting on Scott's review

4. **Summarize**: table format with PR title, author, status, age, CI state
`;
}

function modelCostMonitor(s) {
  return `---
name: model-cost-monitor
description: "Track daily model API spend across OpenRouter, Anthropic, OpenAI"
---

# Model Cost Monitor

> Signal: ${s.signal}

## Steps

1. **OpenRouter** — check activity page or API for today's spend
2. **Anthropic** — check usage dashboard
3. **OpenAI/Codex** — check usage

## Output
Single summary: total spend today, by provider, trend vs yesterday.
Flag if daily spend exceeds $50.
`;
}

function credentialAudit(s) {
  return `---
name: credential-audit
description: "Weekly audit of Access vault — expiring keys, unused creds"
---

# Credential Audit

> Signal: ${s.signal}

## Steps

1. **Load env** — \`source ~/.access-moran-bot.env\`
2. **Check each key** — test that API keys still authenticate
3. **Flag expiring** — any keys with known expiry dates approaching
4. **Unused check** — cross-reference with Cowork.ai activity — which services haven't been accessed in 30+ days?

## Output
Table: service, key status (ok/expiring/unused), last used, action needed.
`;
}

function slackHealth(s) {
  return `---
name: slack-integration-health
description: "Monitor Slack app/bot health, token expiry, rate limits"
---

# Slack Integration Health

> Signal: ${s.signal}

## Steps

1. **Test bot token** — post a test message or call auth.test
2. **Check rate limit headers** — are we near any limits?
3. **Verify webhook endpoints** — are they responding?

## Output
Status: healthy/degraded/down for each Slack integration.
`;
}

function expenseMonitor(s) {
  return `---
name: expense-monitor
description: "Daily Brex spend summary — flag unusual charges"
---

# Expense Monitor

> Signal: ${s.signal}

## Steps
1. Check Brex API or dashboard for today's transactions
2. Compare against typical daily spend
3. Flag anything unusual (>2x average, new vendors, etc.)

## Output
Today's spend, top charges, any flags.
`;
}

function videoCataloger(s) {
  return `---
name: video-cataloger
description: "Index local recordings by date/project/participant"
---

# Video Cataloger

> Signal: ${s.signal}

## Steps
1. Scan ~/Movies, ~/Desktop, ~/Downloads for .mov/.mp4 files
2. Extract date from filename or file metadata
3. Cross-reference with calendar to identify meeting/project
4. Output an index file

## Output
Markdown table: filename, date, project, duration, size.
`;
}

function tabAudit(s) {
  return `---
name: tab-audit
description: "Flag Chrome tabs open >2hrs, suggest save-or-close"
---

# Tab Audit

> Signal: ${s.signal}

## Steps
1. Use Chrome DevTools MCP to list open tabs
2. Check how long each has been open (from activity_sessions)
3. Flag tabs open >2 hours
4. Suggest: bookmark and close, or keep with reason

## Output
List of stale tabs with suggested action.
`;
}

function bookmarkManager(s) {
  return `---
name: bookmark-manager
description: "Auto-organize bookmarks by project from browser history"
---

# Bookmark Manager

> Signal: ${s.signal}

## Steps
1. Read recent browser URLs from Cowork.ai activity
2. Cluster by domain/project
3. Suggest bookmark folder structure
4. Optionally create bookmarks via Chrome extension

## Output
Suggested folder structure with URLs grouped by project.
`;
}
